### ISSUE TITLE
1.0.0 release

### ISSUE THREAD

**Issue by rgbkrk** [nteract/transformime#17]
From gitter, the things we need for this "release"

## Documentation

* [x] Basic usage of the library
* [x] Usage with `transformRichest` and `transformAll`
* [X] Creating custom renderers (see [transformime commonmark](https://github.com/nteract/transformime-commonmark))

## Testing

* [X] Cover `transformime.js`
* [x] Cover the renderers

**Comment by rgbkrk** [comment]
Most of these can end up in https://github.com/nteract/transformime-jupyter-transformers now.

**Comment by rgbkrk** [comment]
Migrated the mimetype requirements to https://github.com/nteract/transformime-jupyter-transformers/issues/2

**Comment by jdfreder** [comment]
Heading over to transformime jupyter...  Are we near a release?  We should meetup somewhere here at PyData to discuss.

**Comment by rgbkrk** [comment]
Since I was experimenting with changing the interface a bit more (including `mimetype` in the response from `transformRichest` and `transformAll`), I figured we'd meet up to discuss. I want to toss the fallbackRenderer too and leave that to the callee.

**Comment by jdfreder** [comment]
From our talk, semi-in-person, we decided to go with `{mimetype: mimetype, el: HTMLElement}`

**Comment by rgbkrk** [comment]
:shipit:

```
$ npm version major
v1.0.0
$ npm publish
+ transformime@1.0.0
$ git push upstream master
Counting objects: 3, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 291 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
To git@github.com:nteract/transformime.git
   b5d3354..00a36f5  master -> master
$ git push upstream master --tags
Counting objects: 1, done.
Writing objects: 100% (1/1), 155 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
To git@github.com:nteract/transformime.git
 * [new tag]         v1.0.0 -> v1.0.0
```
