### ISSUE TITLE
Renderer -> Transformer

### ISSUE THREAD

**Issue by rgbkrk** [nteract/transformime#19]
Pedantically, it's the browser that's doing the rendering. We're transforming to HTMLElements.

To us, mime bundles are HTMLElements in disguise. I'll show myself out.

I vote we change over to calling these transformers. Yes, I'm being pedantic and bike shedding just a lil. Thoughts?

**Comment by willwhitney** [comment]
I accidentally wrote `transformer.render` instead of `transformer.transform` earlier because of the naming difference. Transformers makes more sense to me, so let's do it.

**Comment by rgbkrk** [comment]
While I'm at it, what about the package names?

`transformer-markdown` ?

**Comment by rgbkrk** [comment]
Ok, cool. Let's just do it. I'll switch stuff up.

**Comment by jdfreder** [comment]
:+1:
