### ISSUE TITLE
HTML mimetype should execute script, or provide the option to do so.

### ISSUE THREAD

**Issue by jdfreder** [nteract/transformime#27]
Useful info: http://stackoverflow.com/questions/2592092/executing-script-elements-inserted-with-innerhtml

**Comment by rgbkrk** [comment]
:+1:

**Comment by rgbkrk** [comment]
I think what we want it to do is go back through and re-place the `<script>` elements.

Pseudo code:

```
scripts = el.querySelectorAll("script")
// Take each of these and re-insert them into this element
```

**Comment by rgbkrk** [comment]
At least in jsdom it appears to, but I'm assuming Chrome wouldn't:


```
> window.y
undefined
> p = ht.transform("<script>y=3</script>", document)
> el = p.valueOf()
> window.y
undefined
>  document.querySelector("body").appendChild(el)
> window.y
3
```

**Comment by rgbkrk** [comment]
Yup, chrome is different.

```javascript
> div = document.createElement("div")
<div>​</div>​
> div.innerHTML = "<script>x=2</script>"
"<script>x=2</script>"
> x
VM530:2 Uncaught ReferenceError: x is not defined
    at <anonymous>:2:1
    at Object.InjectedScript._evaluateOn (<anonymous>:895:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)
    at Object.InjectedScript.evaluate (<anonymous>:694:21)(anonymous function) @ VM530:2InjectedScript._evaluateOn @ VM244:895InjectedScript._evaluateAndWrap @ VM244:828InjectedScript.evaluate @ VM244:694
> document.querySelector('body').appendChild(div)
<div>​…​</div>​
> x
VM705:2 Uncaught ReferenceError: x is not defined
    at <anonymous>:2:1
    at Object.InjectedScript._evaluateOn (<anonymous>:895:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)
    at Object.InjectedScript.evaluate (<anonymous>:694:21)
```

**Comment by rgbkrk** [comment]
This is one of those things where testing against jsdom is not the most helpful. We probably need to get our karma runners in a good place (and possibly use electron for our DOM environment).

**Comment by rgbkrk** [comment]
:boom: https://github.com/jprichardson/electron-mocha

**Comment by jdfreder** [comment]
Yeah, we'll definitely need some real browser tests.

**Comment by rgbkrk** [comment]
From our in person discussion, it sounded like we can have two modes for these:

* Unsafe script executor
* Caja enabled HTML transformer (?)

**Comment by karissa** [comment]
For caja stuff see https://developers.google.com/caja/docs/gettingstarted/. Doesn't look that hard, but I did the first one here: https://github.com/nteract/transformime/pull/32

**Comment by karissa** [comment]
As for testing, a lot of us node nerds a very high opinion of tape and zuul for simplicity and ease of onboarding. I did a demo here: https://github.com/nteract/transformime/blob/html-scripts/test/html.transformer.test.js

The only problem is your babel transforms make this difficult so I just fell back to lib/transformime. Not sure how to fix that, kinda newb at the es6/babel stuff..

**Comment by karissa** [comment]
So, the test failed because mocha doesn't know anything about 'document': https://travis-ci.org/nteract/transformime/builds/83837457

Another great thing about tape is that it can do both node and browser tests with the same syntax!

**Comment by rgbkrk** [comment]
Done by #29!
