### ISSUE TITLE
Adapt tests to work across karma multi-browser runs

### ISSUE THREAD

**Issue by rgbkrk** [nteract/transformime#29]
Right now there are a few segments where we declare and use somewhat `jsdom` specific things. There's got to be a way for us to abstract those out and pre-run some `document`, `window`, and `HTMLElement` setup only when run in node, while assuming they're there for Browsers.

**Comment by karissa** [comment]
how about this? https://github.com/defunctzombie/zuul/wiki/quickstart

**Comment by karissa** [comment]
Oops, cross commented here: #27

**Comment by rgbkrk** [comment]
Using zuul + sauce labs now!
