### ISSUE TITLE
Bring in transformime-commonmark and the jupyter transforms in as defaults

### ISSUE THREAD

**Issue by rgbkrk** [nteract/transformime#40]
Let's make this simpler by bringing those in as part of the default set.

**Comment by rgbkrk** [comment]
* [transformime-commonmark](https://github.com/nteract/transformime-commonmark)
* [transformime-jupyter-transformers](https://github.com/nteract/transformime-jupyter-transformers)

**Comment by lgeiger** [comment]
I would like to tackle this issue.

I see two ways of doing this.
We could leave them in their own package and just import them like [here](https://github.com/nteract/transformime-jupyter-transformers/blob/master/src/index.js#L4) or we move everything in this repository and drop `transformime-jupyter-transformers` and `transformime-commonmark`.

I tend towards the second option. What do you think?

**Comment by rgbkrk** [comment]
Second option sounds good to me too.

**Comment by lgeiger** [comment]
I think we should replace the `text/plain` transform with `jupyter/consoletext` in order to handle ANSI colors there as well.

Also we should decide if the default for markdown rendering should stay `commonmark` or if we should use `marked` (I think the notebook uses `marked` at the moment).

**Comment by rgbkrk** [comment]
The notebook uses marked, yet doesn't get much active development. Commonmark is driving a spec, which means I'm more ideologically in favor of it.

/cc @minrk - this largely affects Hydrogen and sidecar since phosphor switched to their own setup.

**Comment by lgeiger** [comment]
I don't feel strongly about `marked` vs. `commonmark`.

But for my understanding `text/plain` should handle ansi as well.

**Comment by rgbkrk** [comment]
I agree with the ansi bits.

**Comment by jasongrout** [comment]
I'm paying attention to what you do here to help guide our decisions in JupyterLab, so thanks for looking into commonmark vs marked, and the ansi stuff.

**Comment by rgbkrk** [comment]
Ok awesome, thanks for speaking up Jason!

**Comment by lgeiger** [comment]
#49
