### ISSUE TITLE
mimebundles can be an array of strings or a string

### ISSUE THREAD

**Issue by rgbkrk** [nteract/transformime#42]
One thing I'm wondering about from the nbformat spec - [mimebundles values can contain a string or an array of strings](https://github.com/jupyter/nbformat/blob/40f770e37ba9f7fd8618827e6298fcb843935d86/nbformat/v4/nbformat.v4.schema.json#L350-L351). Should transformime accept either case or assume that happens above. In the `text/plain` case, it makes sense to just concatenate. For images what's appropriate? Is each string an individual element that needs to be created?

/cc @minrk

**Comment by rgbkrk** [comment]
Based on the multiline case, this should always be the concatenation.

**Comment by minrk** [comment]
it shouldn't handle the list-of-strings case. That can only happen on-disk, never in messages or memory.

**Comment by rgbkrk** [comment]
Ah, ok. That's why this is first time I'm seeing it. Usually I work with just the messages directly and right now I'm working with random notebooks.

**Comment by rgbkrk** [comment]
Thanks Min.

**Comment by rgbkrk** [comment]
[Reference form nbformat docs](http://nbformat.readthedocs.org/en/latest/format_description.html)
