### ISSUE TITLE
API Questions

### ISSUE THREAD

**Issue by rgbkrk** [nteract/transformime#43]
We made `transformRichest` return a `Promise`, with the expectation that we would end up having transforms that had asynchronous processing to perform. One of the reasons was that we thought about having PDF render inline using pdf.js, which would require returning a promise. Since we haven't gone down that avenue, I think we can simplify this to *not* using promises again.

What do you think @jasongrout and @jdfreder?

**Comment by jasongrout** [comment]
I think it's fine to make the transform function async.  That gives flexibility to do things like request extra resources from the server too.

**Comment by jdfreder** [comment]
Like @jasongrout said, I'd leave this API async.  We want people other than us to be able to add transforms without trouble, so we are stuck anticipating what they may do.  Coming from ipywidgets, where we went from sync -> async, I can tell you that the transition is error prone, so we might as well avoid it at the cost of our API being a little more heavy.

**Comment by rgbkrk** [comment]
Cool, thanks. That definitely makes sense and the difficulties experienced in trying to make the transition in ipywidgets helps paint the right picture. Thanks Jason and Jon!
