### ISSUE TITLE
anser does not play well with webpack

### ISSUE THREAD

**Issue by blink1073** [nteract/transformime#52]
I tried to incorporate `anser` into `jupyter-js-ui` [here](https://github.com/jupyter/jupyter-js-ui/pull/86) and ran into this warning from webpack:

```
WARNING in ../~/anser/dist/index.js
Critical dependencies:
1:1021-1028 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ../~/anser/dist/index.js 1:1021-1028
```

It can be avoided by adding `noParse: [/anser\/dist/]` to the webpack config, but I am going to stick with `ansi_up` for now.  I also tried explicitly using `anser/lib`, but that contains ES6 syntax (the `class` keyword).

**Comment by rgbkrk** [comment]
That sounds good for switching back to `ansi_up`. I took some time to transpile `anser` with babel and he still opted to use his dist-it package afterward: https://github.com/IonicaBizau/anser/pull/4

Thanks for reporting. 😠

**Comment by IonicaBizau** [comment]
@rgbkrk @blink1073 Thanks for report. I see the issue. Would it work if we would just babelify the source and do not make any changes? 💭 

I'm not really happy with having babel as direct (dev-)dependency. I will probably add an option in `dist-it`.

**Comment by rgbkrk** [comment]
Thank you.

> Would it work if we would just babelify the source and do not make any changes?

That is correct. The ES5 source (not prepped for the web, prepped for release on npm) is what needs to be available for libraries.

> I'm not really happy with having babel as direct (dev-)dependency. I will probably add an option in dist-it.

Would dist-it be a dev dependency within anser, solely for all the babel setup you want?

**Comment by IonicaBizau** [comment]
> Would dist-it be a dev dependency within anser, solely for all the babel setup you want?

Not really, because I install it globally. Only npm collaborators (those with `npm publish` superpowers) will have to `npm i -g dist-it`.

**Comment by rgbkrk** [comment]
Ah, ok. Thanks for clarifying.

**Comment by IonicaBizau** [comment]
I'm assigning this to me so I won't forget it. In case I don't give you any sign of life in the next days, ping me. 🔔

**Comment by IonicaBizau** [comment]
@blink1073 I transpiled all my js stuff I have on npm and republished it. In particular, `anser` should be now compatible with older versions of Node.js.

I built [`babel-it`](https://github.com/IonicaBizau/babel-it) which actually works like an `npm publish`, but babelifying the code first. :rocket: 

Once you guys confirm that everything is working smoothly, we can close this issue.
Hopefully I didn't break anything.

**Comment by IonicaBizau** [comment]
@rgbkrk Is this still an issue? I noticed a commit made 9 days ago that @lgeiger updated the `anser` dependency to `1.1.0`—which is not bundled anymore. 🚀

**Comment by rgbkrk** [comment]
We've yet to switch back over in transformime-react or https://github.com/nteract/ansi-to-react

**Comment by IonicaBizau** [comment]
Should be fixed here: https://github.com/nteract/ansi-to-react/pull/11 :tada:
