### ISSUE TITLE
ReactElement output

### ISSUE THREAD

**Issue by nelix** [nteract/transformime#74]
Is there much interest in being able to request something that can be passed to React.createElement? 
Would make integrating into react apps easier, and maintaining state where people might be editing but want to see the rest of their view change.
With that you could potentially do things like serialise event handlers and hydrate those too.

**Comment by rgbkrk** [comment]
We do have a react version of this library, called [transformime-react](https://github.com/nteract/transformime-react), it returns a React component you can pass to `React.createElement`. It is a bit outdated though as we ended up moving it into nteract/nteract with the hopes of exporting it as part of a monorepo (:soon: -- doing it early Q1).

What are you hacking on / thinking of?

**Comment by nelix** [comment]
A portfolio/hacky project viewer, a lot like nteract, without any remote or other lang stuff.
I'd like to be able to easily embed react in markdown in react in markdown... etc, and other mime types, and I'd like a repl running in an iframe, so serialisation of these things into react elements is very appealing. 

Love nteract btw.

**Comment by lgeiger** [comment]
@nelix We've recently published our [new transforms](https://github.com/nteract/nteract/tree/master/packages). They are available under the [`@nteract/`](https://www.npmjs.com/search?q=@nteract/transform) name space.
